jwt:
  secretKey: sdfgfgdsfg7sd890fgsdfgsidfjgskdjfhglwut9w834ut90jkfjsdfgw9483utoegdfklgndfgowejt59u6
spring:
  application:
    name: api-gateway
  #api gateway config
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
          filters:
            - StripPrefix=2
            #            - RedirectTo=302, http://codingshuttle.com
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                Enabled: true
        #            - name: Authorization
        #              args:
        #                allowedRoles: ADMIN, SUPER_ADMIN
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/v1/notification/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=X-Custom-Header, Manish
            - name: Authentication
              args:
                Enabled: true


server:
  port: 8080
